const mockNotifications = [
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000001",
    type: "REMINDER",
    time: new Date().toISOString(),
    read: false,
    readTime: null,
    notifData: {
      title: "Morning Workout",
      message: "Time to hit the gym 💪",
      priority: "high",
    },
    groupId: "group-1",
    reminderRefId: "rem-001",
    eventRefId: null,
    userId: "user-123",
    sentNotification: true,
    sentWebPush: false,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000002",
    type: "EVENT_INVITE",
    time: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    read: true,
    readTime: new Date().toISOString(),
    notifData: {
      title: "Project Kickoff",
      message: "You've been invited to Project Kickoff",
      eventDate: "2026-03-01T18:00:00Z",
    },
    groupId: null,
    reminderRefId: null,
    eventRefId: "event-001",
    userId: "user-123",
    sentNotification: true,
    sentWebPush: true,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000003",
    type: "SYSTEM",
    time: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    read: false,
    readTime: null,
    notifData: {
      title: "System Update",
      message: "New features have been deployed 🚀",
    },
    groupId: null,
    reminderRefId: null,
    eventRefId: null,
    userId: "user-123",
    sentNotification: true,
    sentWebPush: true,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000004",
    type: "REMINDER",
    time: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    read: true,
    readTime: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    notifData: {
      title: "Doctor Appointment",
      message: "Appointment at 3:30 PM",
      location: "Downtown Clinic",
    },
    groupId: "health",
    reminderRefId: "rem-002",
    eventRefId: null,
    userId: "user-123",
    sentNotification: true,
    sentWebPush: false,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000005",
    type: "COMMENT",
    time: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    read: false,
    readTime: null,
    notifData: {
      title: "New Comment",
      message: "Sarah commented on your post",
      postId: "post-22",
    },
    groupId: "social",
    reminderRefId: null,
    eventRefId: null,
    userId: "user-123",
    sentNotification: false,
    sentWebPush: false,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000006",
    type: "EVENT_START",
    time: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    read: false,
    readTime: null,
    notifData: {
      title: "Live Webinar Starting",
      message: "Your webinar starts in 10 minutes",
      joinUrl: "/events/event-002",
    },
    groupId: "events",
    reminderRefId: null,
    eventRefId: "event-002",
    userId: "user-123",
    sentNotification: true,
    sentWebPush: true,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000007",
    type: "TASK_ASSIGNED",
    time: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    read: true,
    readTime: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    notifData: {
      title: "New Task Assigned",
      message: "Finish UI notification layout",
      dueDate: "2026-02-28T23:59:00Z",
    },
    groupId: "work",
    reminderRefId: null,
    eventRefId: null,
    userId: "user-123",
    sentNotification: true,
    sentWebPush: false,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000008",
    type: "REMINDER",
    time: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    read: false,
    readTime: null,
    notifData: {
      title: "Water the Plants",
      message: "Your monstera is thirsty 🌿",
    },
    groupId: "home",
    reminderRefId: "rem-003",
    eventRefId: null,
    userId: "user-123",
    sentNotification: false,
    sentWebPush: false,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000009",
    type: "PAYMENT",
    time: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    read: true,
    readTime: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    notifData: {
      title: "Payment Received",
      message: "$250 received from Client",
      amount: 250,
    },
    groupId: "finance",
    reminderRefId: null,
    eventRefId: null,
    userId: "user-123",
    sentNotification: true,
    sentWebPush: true,
  },
  {
    id: "b1f1c1a2-1111-4a2b-8c1a-000000000010",
    type: "SECURITY",
    time: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    read: false,
    readTime: null,
    notifData: {
      title: "New Login Detected",
      message: "Login from new device",
      device: "Chrome on Linux",
    },
    groupId: null,
    reminderRefId: null,
    eventRefId: null,
    userId: "user-123",
    sentNotification: true,
    sentWebPush: true,
  },
];

export default mockNotifications;
