export const colors = [
  { color: "bg-violet-300" },
  { color: "bg-indigo-300" },
  { color: "bg-emerald-300" },
  { color: "bg-blue-300" },
  { color: "bg-red-300" },
  { color: "bg-pink-300" },
  { color: "bg-orange-300" },
  { color: "bg-teal-300" },
  { color: "bg-yellow-300" },
];

export const holidays = [
  {
    color: "bg-purple-300",
    date: "1/1/2023",
    event: "New Years Day!!",
    id: 1,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-purple-300",
    date: "1/16/2023",
    event: "Martin Luther King Jr Day!!",
    id: 2,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-purple-300",
    date: "2/1/2023",
    event: "Black History Month!!",
    id: 3,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-green-300",
    date: "2/2/2023",
    event: "Groundhog Day!!",
    id: 4,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-red-300",
    date: "2/14/2023",
    event: "Valentines Day!!",
    id: 5,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "2/20/2023",
    event: "Presedents Day!!",
    id: 6,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-yellow-300",
    date: "3/12/2023",
    event: "Daylight Savings Starts",
    id: 7,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-green-300",
    date: "3/17/2023",
    event: "St. Patricks Day!!",
    id: 8,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-yellow-300",
    date: "4/7/2023",
    event: "Good Friday!!",
    id: 9,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-yellow-300",
    date: "4/9/2023",
    event: "Easter Sunday!!",
    id: 10,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-purple-300",
    date: "5/14/2023",
    event: "Mothers Day!!",
    id: 11,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-pink-300",
    date: "5/29/2023",
    event: "Memorial Day!!",
    id: 12,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "6/18/2023",
    event: "Fathers Day!!",
    id: 13,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-blue-300",
    date: "7/4/2023",
    event: "Independance Day!!",
    id: 14,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-blue-300",
    date: "9/4/2023",
    event: "Labor Day!!",
    id: 15,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "10/31/2023",
    event: "Halloween",
    id: 16,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "11/23/2023",
    event: "Thanksgiving!!",
    id: 17,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-green-300",
    date: "12/25/2023",
    event: "Christmas!!",
    id: 18,
    reminders: false,
    repeat: false,
    time: false,
  },
];
