export const colors = [
  { color: "bg-violet-300" },
  { color: "bg-indigo-300" },
  { color: "bg-emerald-300" },
  { color: "bg-blue-300" },
  { color: "bg-red-300" },
  { color: "bg-pink-300" },
  { color: "bg-orange-300" },
  { color: "bg-teal-300" },
  { color: "bg-yellow-300" },
];

export const repeatOptions = [
  "Daily",
  "Weekly",
  "Bi Weekly",
  "Monthly",
  "Yearly",
  "Custom",
];

export const weekDays = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const holidays = [
  {
    color: "bg-purple-300",
    date: "1/1/2023",
    summary: "New Years Day!!",
    id: 1,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-purple-300",
    date: "1/16/2023",
    summary: "Martin Luther King Jr Day!!",
    id: 2,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-purple-300",
    date: "2/1/2023",
    summary: "Black History Month!!",
    id: 3,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-green-300",
    date: "2/2/2023",
    summary: "Groundhog Day!!",
    id: 4,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-red-300",
    date: "2/14/2023",
    summary: "Valentines Day!!",
    id: 5,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "2/20/2023",
    summary: "Presedents Day!!",
    id: 6,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-yellow-300",
    date: "3/12/2023",
    summary: "Daylight Savings Starts",
    id: 7,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-green-300",
    date: "3/17/2023",
    summary: "St. Patricks Day!!",
    id: 8,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-yellow-300",
    date: "4/7/2023",
    summary: "Good Friday!!",
    id: 9,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-yellow-300",
    date: "4/9/2023",
    summary: "Easter Sunday!!",
    id: 10,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    kind: "summary",
    color: "bg-purple-300",
    date: "5/14/2023",
    summary: "Mothers Day!!",
    description: "Happy Mothers Day!",
    id: 11,
    reminders: {
      reminder: false,
    },
    repeats: {
      repeat: false,
      howOften: "yearly",
      nextDate: "5/14/2024",
    },
    location: "",
    time: false,
  },
  {
    color: "bg-pink-300",
    date: "5/29/2023",
    summary: "Memorial Day!!",
    id: 12,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "6/18/2023",
    summary: "Fathers Day!!",
    id: 13,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-blue-300",
    date: "7/4/2023",
    summary: "Independance Day!!",
    id: 14,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-blue-300",
    date: "9/4/2023",
    summary: "Labor Day!!",
    id: 15,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "10/31/2023",
    summary: "Halloween",
    id: 16,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-orange-300",
    date: "11/23/2023",
    summary: "Thanksgiving!!",
    id: 17,
    reminders: false,
    repeat: false,
    time: false,
  },
  {
    color: "bg-green-300",
    date: "12/25/2023",
    summary: "Christmas!!",
    id: 18,
    reminders: false,
    repeat: false,
    time: false,
  },
];
